// Icon mapping from lucide-react to react-icons
import {
  FiShoppingCart,
  FiUser,
  FiMenu,
  FiX,
  FiSearch,
  FiHeart,
  FiStar,
  FiPlus,
  FiMinus,
  FiEdit,
  FiTrash2,
  FiEye,
  FiEyeOff,
  FiChevronDown,
  FiChevronUp,
  FiChevronLeft,
  FiChevronRight,
  FiArrowLeft,
  FiArrowRight,
  FiHome,
  FiSettings,
  FiLogOut,
  FiFilter,
  FiGrid,
  FiList,
  FiCheck,
  FiAlertCircle,
  FiInfo,
  FiUpload,
  FiDownload,
  FiMail,
  FiPhone,
  FiMapPin,
  FiCalendar,
  FiClock,
  FiDollarSign,
  FiPackage,
  FiTruck,
  FiUsers,
  FiBarChart,
  FiPieChart,
  FiTrendingUp,
  FiRefreshCw,
  FiSave,
  FiCopy,
  FiExternalLink,
  FiImage,
  FiVideo,
  FiFile,
  FiFolder,
  FiLock,
  FiUnlock,
  FiShield,
  FiGlobe,
  FiWifi,
  FiDatabase,
  FiServer,
  FiMonitor,
  FiSmartphone,
  FiTablet,
  FiPrinter,
  FiCamera,
  FiMic,
  FiVolume2,
  FiVolumeX,
  FiPlay,
  FiPause,
  FiStop,
  FiSkipBack,
  FiSkipForward,
  FiRepeat,
  FiShuffle,
  FiMaximize,
  FiMinimize,
  FiRotateCcw,
  FiRotateCw,
  FiZoomIn,
  FiZoomOut,
  FiMove,
  FiCrop,
  FiScissors,
  FiPenTool,
  FiType,
  FiAlignLeft,
  FiAlignCenter,
  FiAlignRight,
  FiAlignJustify,
  FiBold,
  FiItalic,
  FiUnderline,
  FiLink,
  FiUnlink,
  FiCode,
  FiTerminal,
  FiGitBranch,
  FiGitCommit,
  FiGitMerge,
  FiGitPullRequest,
  FiBookmark,
  FiBook,
  FiBookOpen,
  FiLayers,
  FiLayout,
  FiSidebar,
  FiColumns,
  FiRows,
  FiSquare,
  FiCircle,
  FiTriangle,
  FiHexagon,
  FiOctagon,
  FiMoreHorizontal,
  FiMoreVertical
} from 'react-icons/fi';

// Icon mapping object
export const iconMap = {
  // Shopping & E-commerce
  ShoppingCart: FiShoppingCart,
  ShoppingBag: FiShoppingCart,
  Package: FiPackage,
  Truck: FiTruck,
  DollarSign: FiDollarSign,
  
  // User & Authentication
  User: FiUser,
  Users: FiUsers,
  LogOut: FiLogOut,
  Lock: FiLock,
  Unlock: FiUnlock,
  Shield: FiShield,
  Eye: FiEye,
  EyeOff: FiEyeOff,
  
  // Navigation & UI
  Menu: FiMenu,
  X: FiX,
  Search: FiSearch,
  Home: FiHome,
  Settings: FiSettings,
  ChevronDown: FiChevronDown,
  ChevronUp: FiChevronUp,
  ChevronLeft: FiChevronLeft,
  ChevronRight: FiChevronRight,
  ArrowLeft: FiArrowLeft,
  ArrowRight: FiArrowRight,
  MoreHorizontal: FiMoreHorizontal,
  MoreVertical: FiMoreVertical,
  
  // Actions
  Plus: FiPlus,
  Minus: FiMinus,
  Edit: FiEdit,
  Trash2: FiTrash2,
  Check: FiCheck,
  Save: FiSave,
  Copy: FiCopy,
  Upload: FiUpload,
  Download: FiDownload,
  RefreshCw: FiRefreshCw,
  
  // Content & Media
  Heart: FiHeart,
  Star: FiStar,
  Image: FiImage,
  Video: FiVideo,
  File: FiFile,
  Folder: FiFolder,
  Camera: FiCamera,
  
  // Communication
  Mail: FiMail,
  Phone: FiPhone,
  MapPin: FiMapPin,
  ExternalLink: FiExternalLink,
  Globe: FiGlobe,
  
  // Time & Calendar
  Calendar: FiCalendar,
  Clock: FiClock,
  
  // Alerts & Status
  AlertCircle: FiAlertCircle,
  Info: FiInfo,
  
  // Layout & Display
  Filter: FiFilter,
  Grid: FiGrid,
  List: FiList,
  Layout: FiLayout,
  Sidebar: FiSidebar,
  Columns: FiColumns,
  Rows: FiRows,
  
  // Charts & Analytics
  BarChart: FiBarChart,
  PieChart: FiPieChart,
  TrendingUp: FiTrendingUp,
  
  // Technology
  Database: FiDatabase,
  Server: FiServer,
  Monitor: FiMonitor,
  Smartphone: FiSmartphone,
  Tablet: FiTablet,
  Wifi: FiWifi,
  Terminal: FiTerminal,
  Code: FiCode,
  
  // Text & Formatting
  Type: FiType,
  AlignLeft: FiAlignLeft,
  AlignCenter: FiAlignCenter,
  AlignRight: FiAlignRight,
  AlignJustify: FiAlignJustify,
  Bold: FiBold,
  Italic: FiItalic,
  Underline: FiUnderline,
  Link: FiLink,
  Unlink: FiUnlink,
  
  // Shapes
  Square: FiSquare,
  Circle: FiCircle,
  Triangle: FiTriangle,
  Hexagon: FiHexagon,
  Octagon: FiOctagon,
  
  // Media Controls
  Play: FiPlay,
  Pause: FiPause,
  Stop: FiStop,
  SkipBack: FiSkipBack,
  SkipForward: FiSkipForward,
  Repeat: FiRepeat,
  Shuffle: FiShuffle,
  Volume2: FiVolume2,
  VolumeX: FiVolumeX,
  
  // Tools & Editing
  Move: FiMove,
  Crop: FiCrop,
  Scissors: FiScissors,
  PenTool: FiPenTool,
  RotateCcw: FiRotateCcw,
  RotateCw: FiRotateCw,
  ZoomIn: FiZoomIn,
  ZoomOut: FiZoomOut,
  Maximize: FiMaximize,
  Minimize: FiMinimize,
  
  // Version Control
  GitBranch: FiGitBranch,
  GitCommit: FiGitCommit,
  GitMerge: FiGitMerge,
  GitPullRequest: FiGitPullRequest,
  
  // Bookmarks & Reading
  Bookmark: FiBookmark,
  Book: FiBook,
  BookOpen: FiBookOpen,
  
  // Layers & Organization
  Layers: FiLayers,
  
  // Hardware
  Printer: FiPrinter,
  Mic: FiMic
};

// Helper function to get icon component
export const getIcon = (iconName, defaultIcon = FiCircle) => {
  return iconMap[iconName] || defaultIcon;
};

// Export default icon for fallback
export default FiCircle;
